title: ROHAN LONE 
logo: /assets/images/DP.png

description: > 
 <p><em><b class="term">A deep learner, <br /></em></b>
 <em><b class="term">a designer. <br /></em></b>
 </p>
 
 <br>
 <a href="https://www.linkedin.com/in/rohanlone/">LinkedIn Profile</a> 
 <br>
 <a href="https://github.com/RohanLone/">Github Profile</a> 
 <br>
 [Email](mailto:lonerohans@gmail.com
theme: jekyll-theme-minimal
